# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

add_cols_cpp <- function(mat) {
    .Call(`_quickmatsums_add_cols_cpp`, mat)
}

add_rows_cpp <- function(mat) {
    .Call(`_quickmatsums_add_rows_cpp`, mat)
}

